# Generated by Django 4.1.7 on 2023-03-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='flavour',
            new_name='flavor',
        ),
    ]
