# Generated by Django 4.1.7 on 2023-03-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='productvariante',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop'),
        ),
    ]
