# Generated by Django 4.1.7 on 2023-03-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_flavour_productvariant_flavor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='weight',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='size',
            new_name='option_name',
        ),
    ]
