# Generated by Django 4.1.7 on 2023-03-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_stock_productvariante_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariante',
            old_name='produit',
            new_name='product',
        ),
    ]
