# Generated by Django 4.1.7 on 2023-03-11 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_weight_productvariant_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='option_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.optionname', verbose_name="Nom de l'option"),
        ),
    ]
