# Generated by Django 4.1.7 on 2023-03-11 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_optionname_alter_productvariant_option_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Panier'},
        ),
        migrations.AlterModelOptions(
            name='optionname',
            options={'verbose_name': "Nom de l'option de produit"},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='vairant_slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Nom du produit'),
        ),
    ]
