# Generated by Django 4.1.7 on 2023-03-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_cart_options_alter_optionname_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='vairant_slug',
            new_name='variant_slug',
        ),
    ]
