# Generated by Django 4.1.7 on 2023-05-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_vairant_slug_productvariant_variant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variant_slug',
            field=models.SlugField(blank=True, default='', verbose_name='Slug de la variante'),
        ),
    ]
